### ISSUE TITLE
Question on: "Avoid defining apply methods on classes"

### ISSUE THREAD

**Issue by tomer-ben-david** [databricks/scala-style-guide#10]
didn't you mean "Avoid defining apply methods on **objects**"

**Comment by rxin** [comment]
I think depending on the definition of "objects". Basically apply on companion objects as factory methods makes a lot of sense, but apply defined within a "class" could be very confusing to readers.

**Comment by tomer-ben-david** [comment]
aha i agree! :+1:  thanks.
