### ISSUE TITLE
Adding Korean version of guide line.

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/scala-style-guide#22]
It would be great if there is a Korean version of this.

If you accept this, I would like to try because I am Korean as you know :)

**Comment by xohzzwn6kcj9** [comment]
+1

**Comment by HyukjinKwon** [comment]
I just translated it [here](https://github.com/HyukjinKwon/scala-style-guide/blob/master/README-KO.md) in my forked repository.
I am leaving this comment as I am sure there are some Korean guys who want this although it might not be officially accepted.

If there is none who specks Korean in Databricks, then I would like a second reviewer to take a look this.
If you are okay, [Kevin (Sangwoo) Kim](https://github.com/swkimme) will take a look closer at the document. He is a commiter at Apache Zeppelin and also made some contributions at Spark. Also, he feels convenient with both English and Korean.

If it sounds great, I will initiate this process by adding him to my forked repository (I already talked to him).

**Comment by RetrieverJo** [comment]
+1

**Comment by sunghwanJo** [comment]
+1

**Comment by kty1965** [comment]
+1

**Comment by kcyang** [comment]
+1

**Comment by mindwing** [comment]
+1

**Comment by swkimme** [comment]
+1, Great job!

**Comment by finetea** [comment]
+1, d^^b

**Comment by kgcrom** [comment]
:+1:

**Comment by minkyoungkook** [comment]
+1 WOW

**Comment by hey-jude** [comment]
:+1:

**Comment by rxin** [comment]
I think it's a good idea. Let me get somebody that understands Korean to read over the translation ...

**Comment by rxin** [comment]
Actually @HyukjinKwon can you submit a pull request? It'd be easier to "review" that way.

**Comment by HyukjinKwon** [comment]
Yeap I will open a PR for this.

**Comment by HyukjinKwon** [comment]
Fixed in https://github.com/databricks/scala-style-guide/pull/23
