### ISSUE TITLE
Revisit non-scalaish recommendations

### ISSUE THREAD

**Issue by stevendobay** [databricks/scala-style-guide#29]
Hi guys, 

There is a really strong statement here: https://github.com/databricks/scala-style-guide#recursion-and-tail-recursion

> Avoid using recursion,...

...then the author proceeds to recommend a for loop instead of a tail recursive solution. Scala is an (impure) functional language where it's recommended to solve you problems with recursion and tailrec will outperform a for loop solution at any time: http://ideone.com/J13mbU
The linked test is a simplistic benchmarking on using for loop, while loop and a tail rec function to sum the first 1M integers: the for loop takes 75x(!) and the while loop 1.75x more time than the solution with tailrec.
In nanoseconds:
139091940 : for loop
3254375     : while loop
1853058     : tail rec

In Scala the only place for the "for loop" is when you want to block your Future(s) - which isn't recommended neither - or when you're using high level language constructs with scalaz(https://github.com/scalaz/scalaz).

It seems like the author tries to disgust the reader with boilerplate:

```scala
def max(data: Array[Int]): Int = {
  @tailrec
  def max0(data: Array[Int], pos: Int, max: Int): Int = {
    if (pos == data.length) {
      max
    } else {
      max0(data, pos + 1, if (data(pos) > max) data(pos) else max)
    }
  }
  max0(data, 0, Int.MinValue)
}
```

This is how you do it with Scala and @tailrec:

```scala
def max(data: Array[Int]): Option[Int] = {
  @tailrec def getMax(pos: Int, max: Int): Int =
    if(pos == data.size) max 
    else getMax(pos + 1, if(data(pos) > max) data(pos) else max)

  if(data.isEmpty) None else Some(getMax(1, data(0)))
}
```

[**Option vs null**](https://github.com/databricks/scala-style-guide#option-and-null)

In Scala, the concept of "null" is almost taboo, revisit http://www.lihaoyi.com/post/StrategicScalaStylePracticalTypeSafety.html#scalazzi-scala

[**Java features**](https://github.com/databricks/scala-style-guide#java-features-missing-from-scala)
  
  1.  Static fields - with companion objects
  2.  Static inner classes - with companion objects
  3.  Java enums - by specific libraries
  4.  Annotations - http://docs.scala-lang.org/overviews/reflection/annotations-names-scopes.html

[**"Safe" mutable access**](https://github.com/databricks/scala-style-guide#explicit-synchronization-vs-concurrent-collections)

The mentioned 3 ways are primitive and too javaish. There is no safe way to handle mutable memory. One commonly accepted way is to encapsulate the state with actors(http://akka.io/) and another is to implement uniqueness types(http://lampwww.epfl.ch/~phaller/capabilities.html).

[**Apply methods**](https://github.com/databricks/scala-style-guide#apply-method)

> Avoid defining apply methods on classes. These methods tend to make the code less readable, especially for people less familiar with Scala.

It's used as the indexing operator - pretty common in Scala and it can remove lots of boilerplate. Remember: Scala isn't Java.

[**Operators...**](https://github.com/databricks/scala-style-guide#symbolic-methods-operator-overloading)

> Do NOT use symbolic method names

It's ok to use sane operators - we've scaladoc and stuff.

Also, 

> stream1 >>= stream2 ... stream1.join(stream2)

the  ">>=" is flatMap, not join(or flatten) and these things are quite useful for people using scalaz/cats.

[**Concurrent maps**](https://github.com/databricks/scala-style-guide#scala-concurrentmap)

> Prefer java.util.concurrent.ConcurrentHashMap over scala.collection.concurrent.Map. 

Avoid "concurrent maps" - they're useless. There are better ways for local key-value stores.

**Comment by aarondav** [comment]
Hi, I was curious about your benchmark, so I made `n` a bit higher (100x) and reran each section a few times. The while loop got JIT'd on the third run and ended up taking 373 nanoseconds (this is dominated by the System.nanoTime call itself), but the tailrec continued to take ~35 milliseconds, and the for loop around 300 milliseconds.

**Comment by rxin** [comment]
@stevendobay thanks for the feedback. This is great. Just some responses below:

0. Most of the points in the guide you brought up actually come with qualifiers or caveats. For example, option vs null: "For performance sensitive code, prefer null over Option, in order to avoid virtual method calls and boxing. Label the nullable fields clearly with Nullable."

1. Tail recursion: all tail recursion optimization is doing is to optimize tail recursive function calls into while loops, so there isn't really any performance benefits of tail recursion over while loops. It has some performance benefits over for loops due to Scala's bad implementation of for loops. @aarondav has already demonstrated this.

2. As far as I know, there is no way to define static fields in Scala, even with companion objects. vals are turned into static functions, rather than fields. See https://issues.scala-lang.org/browse/SI-4581

3. Yes, actors are great, but there are times when you need synchronization primitives or mutable state management (e.g. when implementing actors).

4. "the >>=" is a flatMap or a join: Please see http://docs.scala-lang.org/style/naming-conventions.html#symbolic_method_names "Thus, it is acceptable to define a >>= method for joining two monads, but it is not acceptable to define a << method for writing to an output stream."

5. It's great that you never use concurrent maps, but a lot of other people do and they do have their places.

Again, I'd like to draw your attention to the beginning of the guide: "Scala is an incredibly powerful language that is capable of many paradigms. We have found that the following guidelines work well for us on projects with high velocity. Depending on the needs of your team, your mileage might vary."

**Comment by stevendobay** [comment]
Hey @aarondav! I've simply multiplied n here: http://ideone.com/GrbTB6

**Comment by stevendobay** [comment]
Hi @rxin!
Reading your comment and the guide I've realized the guide is trying to be *truly* compatible with java. With this in mind it sounds reasonable. The entire article could be divided into three parts: (some) recommendations from the original scala style guide, java compatibility and beginner-friendly style.

1. I knew you about the caveats of Option but I'm concerned more about the safety.

2. Yes, that's tail call optimization but Scala's while loop won't be optimized by the JIT always. Scala's for loop isn't a for loop but a macro-based behavioural trait on (foreach | (map (+flatMap) (+filter)). It isn't bad but a high level language construct. Besides these, my concern was more about the standard style than small differences between the while loop and tail rec functions - you either use the for loop with not so good performance or use the while loop introducing a lot of 'var's and non of these solutions relates with neither Scala nor FP. 

3. Yes, these one is about the compatibility too - but for pure Scala code it isn't recommended.

4. How often we implement actors?

5. Your interpretation was reasonable - the sentence you've cited is originally wrong. Maybe, we can't really express what's flatMap(flattening and mapping?). For example, it's alternative names are "bind" and "chain" - just monad stuff. 

6. "concurrent maps" are mutable memory which should be handled carefully - or are they trustable? I'm really interested in their use cases where one can't get rid of them in pure Scala code. See, I'm trying to collect data about every use case of mutable data in Scala to study them and bring up better alternatives as permanent solutions. Scala doesn't guarantee thread safety for mutable cells as much as [Rust](http://manishearth.github.io/blog/2015/05/30/how-rust-achieves-thread-safety/), [Nim](http://nim-lang.org/docs/manual.html#parallel-spawn) or [Clean](http://ftp.cs.ru.nl/SoftwEng.FunctLang/papers/2008/vrie08-IFL07-UniquenessTypingSimplified.pdf). We need to develop ourself at this place.

**Comment by stevendobay** [comment]
Hi @aarondav, I've made a new little test: http://ideone.com/TL8GdQ

The results on Scala 2.11.8 + OpenJDK 1.8.0_91, i7-4712MQ

> ~ $ scala -i Main.scala
> Loading Main.scala...
> defined object Main
> 
> Welcome to Scala 2.11.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_91).
> Type in expressions for evaluation. Or try :help.
> 
> scala> Main.main(Array())
> 62951887 : for loop
> 64789284 - while loop
> 36921434 : tail rec

differs from all previous results.

**Comment by rxin** [comment]
@stevendobay you should use jmh.

**Comment by stevendobay** [comment]
@rxin yes, but no. I can agree that tail rec functions' performance should be equivalent to while loop. But it wasn't just about performance - paradigm is more important. And this guide is more like a how-to program in Java with Scala than an actual Scala style guide. Most Scala features' usage is either unadvised or strongly restricted here(which also questions the place of Scala at this project). You should call it "java-compatible-scala-style-guide" instead.

**Comment by stevendobay** [comment]
Nevermind, I've seen my concerns/questions has been asked [here](https://www.reddit.com/r/scala/comments/2ze443/a_good_example_of_a_scala_style_guide_by_people/) too. Have a good day!
