### ISSUE TITLE
Encourage to use `==` instead of `===` for writing unit tests.

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/scala-style-guide#36]
`FunSuite` provides `===` for comparison. I see `==` and `===` are used in a mixed way across unit tests. It might be great if this is encouraged documented.

See http://www.scalatest.org/getting_started_with_fun_suite

> ScalaTest lets you use Scala's assertion syntax, but defines a triple equals operator (===) to give you better error messages. The following code would give you an error indicating only that an assertion failed:
> 
> assert(1 == 2)
> Using triple equals instead would give you the more informative error message, "1 did not equal 2":
> 
> assert(1 === 2)

**Comment by aarondav** [comment]
As of I think Scala 2.10, ScalaTest's `assert` is a macro which does print nice error messages. If you're working in a 2.10+ codebase, I would recommend double equals, as triple equals can be hard to remember, especially when it's unnecessary.

**Comment by HyukjinKwon** [comment]
@aarondav Thank you so much for your comment! 
I feel like it would be great if it is documented regardless of which one is preferred.

**Comment by HyukjinKwon** [comment]
If it does not matter, then I would like to close anyway.

**Comment by aarondav** [comment]
Feel free to add a section recommending `==` -- I think having a guideline here is very reasonable, especially since there's some history behind it.

**Comment by HyukjinKwon** [comment]
Hi, @aarondav, 
I just simply run the tests as below (my scala version is 2.11.6):

- `assert(1 == 2)`

  ```
  org.scalatest.exceptions.TestFailedException was thrown.
  ```

- `assert(1 === 2)`

  ```
  1 did not equal 2
  ```

I ran this within my local and then also tried with unit tests in Spark.

Am I missing something..?

**Comment by HyukjinKwon** [comment]
But it seems okay with other comparisons. If you think it is fine, I can submit a PR with saying things such as ...

 "... `==` is encouraged because triple equals can be hard to remember, especially when it's unnecessary and this might confuse newbies of Scala developers ...".

**Comment by HyukjinKwon** [comment]
Hm.. cc @rxin too. Do you have any preference or think it is something we should not bother for now?

**Comment by rxin** [comment]
I don't have a strong preference. It doesn't really hurt my eye ...

**Comment by HyukjinKwon** [comment]
Let me close this for now. I will reopen when I happen to get a better reason.
