### ISSUE TITLE
Discourage changing external API's method signature for binary compatibility

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/scala-style-guide#46]
It seems we mention about source compatibility such as in https://github.com/databricks/scala-style-guide#varargs.

However, maybe, we should describe discuraging changing the method signature explicitly.

I have seen several Spark PRs that try to change it and some reviewers say the same comment repeatedly. Also, IMHO, they seem not describing the specific reason sometimes and also I was even asked to break this by few reviewers once.

I think it might be great if that is described here and simply we can leave the link pointer.

To be more concrete, 

If we have both classes as below:

```scala
object A {
  def toString(v: Int): String = v.toString
}
```

```scala
object Main {
  def main(args: Array[String]): Unit = println(A.toString(1))
}
```

We could run as below:

```bash
scalac A.scala
scalac Main.scala
scala Main
```

prints

```
1
```

However, if someone changes the type from `Int` to `Any` as below mistakenly and the newer version of `A.scala` is released as below:

```scala
object A {
  def toString(v: Any): String = v.toString
}
```

```bash
scalac A.scala
scala Main
```

Previously compiled `Main.scala` is broken as below and we need to recompile `Main.scala`:

```
java.lang.NoSuchMethodError: A$.toString(I)Ljava/lang/String;
	at Main$.main(Main.scala:2)
	at Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
```

**Comment by rxin** [comment]
Wouldn't this be caught automatically by MiMa?

**Comment by HyukjinKwon** [comment]
I don't think all the cases are caught because I remember I observed some cases that pass it (if I was not mistaken). Let me try to find some PR references leave the related links.

I will close this by myself if they were actually all caught correctly.

**Comment by HyukjinKwon** [comment]
I see. I was mistaken. It is checking all now - https://issues.apache.org/jira/browse/SPARK-13920 and some cases I saw were actually caught or discussed not to be changed before actually pushing some commits.

Let me rather open another JIRA in Spark if I happened to see this problem. I am closing this. Thanks for your quick response.
