### ISSUE TITLE
Automated checks for CI ?

### ISSUE THREAD

**Issue by chrissng** [databricks/scala-style-guide#49]
Anyone knows of a good scala style checker that is flexible enough to incorporate this style guide? Will be useful for automation / continuous integration. Thanks!

**Comment by zouzias** [comment]
Hey,

You can get Spark's scala style checker config file from 

https://github.com/apache/spark/blob/master/scalastyle-config.xml

and add this in your build.sbt file

```
lazy val compileScalastyle = taskKey[Unit]("compileScalastyle")
compileScalastyle := org.scalastyle.sbt.ScalastylePlugin.scalastyle.in(Compile).toTask("").value
(compile in Compile) <<= (compile in Compile) dependsOn compileScalastyle
```

You might need to double-check that it is in sync with this guide.

**Comment by chrissng** [comment]
Nice find. I'll take a look at it. Thanks!

**Comment by krzysztofnojman** [comment]
Is it affecting performance in larger projects ?
