### ISSUE TITLE
ConcurrentMap qualifications

### ISSUE THREAD

**Issue by dragos** [databricks/scala-style-guide#6]
I find the wording around Scala concurrent collections a bit too harsh. [ConcurrentMap](https://github.com/databricks/scala-style-guide#scala-concurrentmap) is deprecated and it's just an interface. It explicitly documents each method that **is** atomic (including `putIfAbsent`).

I agree with the observation that `TrieMap.getOrElseUpdate` was unfortunately not atomic, but according to [SI-7943](https://issues.scala-lang.org/browse/SI-7943) this was fixed in 2.11.6.

I know this is a coding style that works for the Databricks team, but a lot of people are going to look at it and follow it. I feel at least a link to the ticket and a more nuanced approach would be better.

**Comment by rxin** [comment]
@dragos Do you want to submit a pull request to link to the JIRA ticket?
